server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/intermediario
    username: intermediario
    password: intermediario@25992
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        show-sql: true
  messages:
    always-use-message-format: false
    basename: locale/messages
    encoding: windows-1252
    fallback-to-system-locale: false
    use-code-as-default-message: false
  web:
    resources:
      static-locations: file:storage
  mvc:
    static-path-pattern: /resources/**
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-bank
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    '[org.springframework.security]': debug
application:
  jwt:
    type: "Bearer "
    access-token:
      expiration: 86400000
      secret: wPSUgRCGVzSo29KXvo423iHTb02BiAE4
    refresh-token:
      expiration: 604800000
      secret: CC2g212cI20JmoYH7NFUtA1kBEtd7iQg
    header-authorization: authorization
  storage:
   location: storage
  bai:
    url: http://localhost:8081
    prefix-iban: "AO0200060000"
    access-token: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5OGFlODcwMC1mMjY0LTQ2MDItOTg0MC1jNDc4NWI3YTIyNWMiLCJleHAiOjE3MDc0NjgwODMsInBhcGVsIjoiR2VyZW50ZSBkZSBBZ8OqbmNpYSJ9.ykRBfFY2zsVNZQlq22zyQ-c9fMpy6AOThsUDB_SlYGCaE1MiF9ziCOUjsS0hcIQygL6sXHR_o3TupKHultE-Og
  bfa:
    url: http://localhost:8082
    prefix-iban: "AO0200040000"
    access-token: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3OTA0ZWUwMi1jNTQwLTQ5MTAtODU3Zi0yMGJhNjljN2E1OGEiLCJleHAiOjE3MDc0Njg3OTIsInBhcGVsIjoiR2VyZW50ZSBkZSBBZ8OqbmNpYSJ9.ZqEdA-D6RWx58fwUqR0frytHpo_v_deQwHentd8fXJBWK-Ly28TAWifc04F7j05yvSIWSGmq0duoTa-1UHqK8Q
